services:
  pgdatabase:
    image: postgres:13
    environment:
      POSTGRES_USER=root
      POSTGRES_PASSWORD=root
      POSTGRES_DB=ny_taxi
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

# docker run -it \
# -e POSTGRES_USER=root \
# -e POSTGRES_PASSWORD=root \
# -e POSTGRES_DB=nyc_taxi \
# -v "c:/Sutiwas's Documents/GitHub Projects/data-engineering-zoomcamp/01_docker_terraform/nyc_taxi_data:/var/lib/postgresql/data" \
# -p 5432:5432 \
# postgres:13